#
# SPDX-License-Identifier: Apache-2.0
#
# The jGuard Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#

version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - gradle

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
