//
// SPDX-License-Identifier: Apache-2.0
//
// The jGuard Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.
//
rootProject.name = "sandbox-legacy-library"

// Include the jGuard build to get the plugin and agent
includeBuild("../..") {
  name = "jguard"
}

include "library"
include "app"
